version: "2"
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssword
      - MYSQL_DATABASE=corecruddb
    ports: 
      - "3306:3306"
    networks:
      - mydockernet

  core:
    image: corecrudol1img
    container_name: corecrudol1container
    depends_on:
      - mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssword
    ports:
      - "9080:9080"
    networks:
      - mydockernet
networks:
   mydockernet:
