
server:
  port: ${vcap.application.port:9091}
#url: jdbc:mysql://mysqldb:3306/db_example
#        url: jdbc:mysql://localhost:3306/corecruddb
spring:
   datasource:
        url: jdbc:mysql://mysqldb:3306/corecruddb
        username: root
        password: p@ssword
   jpa:
        generate-ddl: true
