apiVersion: apps/v1
kind: Deployment
metadata:
  name: corecrudsb1-deployment
  labels:
    app: corecrudsb1
spec:
  selector:
    matchLabels:
      app: corecrudsb1
  template:
    metadata:
      labels:
        app: corecrudsb1
    spec:
      containers:
      - name: corecrudsb1-container
        image: docker.io/srranjan007/corecrudsb1img
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: corecrudsb1-service
spec:
  selector:
    app: corecrudsb1
  ports:
  - protocol: TCP
    port: 9091
---
apiVersion: v1
kind: Route
metadata:
  name: corecrudsb1-route
spec:
  to:
    kind: Service
    name: corecrudsb1-service
