

kind: Service
apiVersion: v1
metadata:
  name: corecrudol1svc
  labels:
    app: corecrudol1svc
    lab: k8-lab
spec:
  type: NodePort
  ports:
    - port: 9080
      name: http-9080
      targetPort: http
  selector:
    app: corecrudol1svc
